CREATE TABLE [prodcopystg].[Opportunity]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IsDeleted] [bit] NULL,
[AccountId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name] [nvarchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StageName] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount] [float] NULL,
[Probability] [float] NULL,
[CloseDate] [date] NULL,
[Type] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextStep] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeadSource] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsClosed] [bit] NULL,
[IsWon] [bit] NULL,
[ForecastCategory] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ForecastCategoryName] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CampaignId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasOpportunityLineItem] [bit] NULL,
[Pricebook2Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[LastActivityDate] [date] NULL,
[FiscalQuarter] [int] NULL,
[FiscalYear] [int] NULL,
[Fiscal] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastViewedDate] [datetime] NULL,
[LastReferencedDate] [datetime] NULL,
[HasOpenActivity] [bit] NULL,
[HasOverdueTask] [bit] NULL,
[PLO__c] [bit] NULL,
[Opportunity_Purpose__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Items__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Renewal__c] [bit] NULL,
[Short_Description__c] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Season__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sport__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account_Email__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account_Phone__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reason_Lost__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full_Opportunity_ID__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Football_Relocation_Request__c] [bit] NULL,
[Football_Relocation_Notes__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Do_Not_Call_Warning__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Deposit_Date__c] [date] NULL,
[Do_Not_Solicit_Buck_Cardinal_Gift__c] [bit] NULL,
[Queue_Number__c] [float] NULL,
[F12_STH__c] [bit] NULL,
[Pac_ID__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Price_Level__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Years_STH__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Likelihood_to_Renew_Survey_Response__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[B13_Pick_5__c] [bit] NULL,
[B13_Single_Games__c] [float] NULL,
[B12_Partial__c] [bit] NULL,
[B12_Season_Tickets__c] [bit] NULL,
[B13_B12_Spend__c] [float] NULL,
[Possible_MBB_Spend__c] [bit] NULL,
[F11_STH__c] [bit] NULL,
[F13_Partial__c] [bit] NULL,
[F12_Partial__c] [bit] NULL,
[F11_Partial__c] [bit] NULL,
[F13_Single_Game_Transactions__c] [float] NULL,
[F12_Single_Game_Transactions__c] [float] NULL,
[F11_Single_Game_Transactions__c] [float] NULL,
[F11_F13_Spend__c] [float] NULL,
[Group_Prospect__c] [bit] NULL,
[F12_Family_Plan__c] [bit] NULL,
[F11_Family_Plan__c] [bit] NULL,
[Previous_F14_Opportunity_Reason_Lost__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F14_DEPP3__c] [bit] NULL,
[F14_F15_DEPG__c] [bit] NULL,
[F14_DEPP3_Date__c] [date] NULL,
[Previous_F14_Campaign__c] [nvarchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F13_Group_Spend__c] [float] NULL,
[F12_Group_Spend__c] [float] NULL,
[F13_Group_Picnic_Area__c] [bit] NULL,
[F12_Group_Picnic_Area__c] [bit] NULL,
[F12_Group_USC__c] [bit] NULL,
[F12_Group_WSU__c] [bit] NULL,
[F12_Group_OSU__c] [bit] NULL,
[F14_STH__c] [bit] NULL,
[F14_Pick_3__c] [bit] NULL,
[F13_F12_Spend__c] [float] NULL,
[F14_DEPG_Date__c] [date] NULL,
[F14_Group_Picnic_Area__c] [bit] NULL,
[StubHub_Account_Warning__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F14_Single_Presale_Tier__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F13_Family_Plan__c] [bit] NULL,
[F14_Item__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X16_Off__c] [bit] NULL,
[B14_Deposit_Date__c] [date] NULL,
[S14_STH__c] [bit] NULL,
[V14_STH__c] [bit] NULL,
[S13_STH__c] [bit] NULL,
[S12_STH__c] [bit] NULL,
[S13_Partial__c] [bit] NULL,
[S12_Partial__c] [bit] NULL,
[S13_Group__c] [bit] NULL,
[S12_Group__c] [bit] NULL,
[S13_Spend__c] [float] NULL,
[S12_Spend__c] [float] NULL,
[S14_Other__c] [float] NULL,
[V13_STH__c] [bit] NULL,
[V12_STH__c] [bit] NULL,
[B12_YA__c] [bit] NULL,
[V13_Partial__c] [bit] NULL,
[V12_Partial__c] [bit] NULL,
[V13_Group__c] [bit] NULL,
[V12_Group__c] [bit] NULL,
[V13_Spend__c] [float] NULL,
[V12_Spend__c] [float] NULL,
[V14_Single_Game_Spend__c] [float] NULL,
[V13_V12_Spend__c] [float] NULL,
[V14_Deposit__c] [bit] NULL,
[B13_Season_Tickets__c] [bit] NULL,
[B13_YA__c] [bit] NULL,
[B12_Single_Games__c] [float] NULL,
[B13_Spend__c] [float] NULL,
[B12_Group__c] [bit] NULL,
[B13_Group__c] [bit] NULL,
[B13_Flex__c] [bit] NULL,
[B14_Sweet_16_Campaign__c] [bit] NULL,
[W13_STH__c] [bit] NULL,
[W12_STH__c] [bit] NULL,
[W13_Flex__c] [bit] NULL,
[W12_Flex__c] [bit] NULL,
[W13_Weekend__c] [bit] NULL,
[W12_Weekend__c] [bit] NULL,
[W13_Pick_5__c] [bit] NULL,
[W12_Pick_5__c] [bit] NULL,
[W13_Group__c] [bit] NULL,
[W12_Group__c] [bit] NULL,
[W13_Hybrid__c] [bit] NULL,
[W12_Food_Fun__c] [bit] NULL,
[W13_Single_Games__c] [float] NULL,
[W12_Single_Games__c] [float] NULL,
[W13_W12_Spend__c] [float] NULL,
[W13_Spend__c] [float] NULL,
[Adobe_Unsubscribe__c] [bit] NULL,
[Email_Quarantine__c] [bit] NULL,
[Family_Plan_Only__c] [bit] NULL,
[Parking_Only__c] [bit] NULL,
[Sold_Transferred_All_F14__c] [bit] NULL,
[MBB_STH__c] [bit] NULL,
[Dropped_Seats_for_F14__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tier__c] [float] NULL,
[Likelihood_to_Renew_Rep__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reason_for_Low_Renewal_Likelihood__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Preferred_Renewal_Method__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Relocation_Interest__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Relocation_Notes__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[B14_Final_Push_Already_Has_Tix_For__c] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Preferred_Parking_Lot_s__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Specify_if_Other__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Preferred_Transportation_Method__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home_Phone__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mobile_Phone__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other_Phone__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[B14_Final_Push__c] [float] NULL,
[B14_Final_Push_Total_B01_B09_Amount__c] [float] NULL,
[B14_Final_Push_Paid_B01_B09_Transactions__c] [float] NULL,
[B14_Final_Push_B01_B09_Group_Price_Type__c] [bit] NULL,
[B14_Final_Push_B01_B09_8_Tickets__c] [bit] NULL,
[D14_Spend__c] [float] NULL,
[D13_Spend__c] [float] NULL,
[D14_STH__c] [bit] NULL,
[D13_STH__c] [bit] NULL,
[D14_Partial__c] [bit] NULL,
[D13_Partial__c] [bit] NULL,
[D14_Group_10__c] [bit] NULL,
[D13_Group__c] [bit] NULL,
[D14_D13_Spend__c] [float] NULL,
[D14_Single_Game_Transactions__c] [float] NULL,
[D13_Single_Game_Transactions__c] [float] NULL,
[F14_Games_Scanned_Pac__c] [float] NULL,
[F14_Games_Attended_Survey__c] [float] NULL,
[Attends_with_Friends__c] [bit] NULL,
[Attends_with_Family_Children_Under_18__c] [bit] NULL,
[Attends_with_Family_18__c] [bit] NULL,
[Attends_with_Colleagues_Clients__c] [bit] NULL,
[Attends_with_Groups__c] [bit] NULL,
[Attends_with_Other__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attends_Alone__c] [bit] NULL,
[Drives_to_Games__c] [bit] NULL,
[Likelihood_to_Park_in_STH_Only_Lot_1_5__c] [float] NULL,
[Likelihood_to_Recommend_0_10__c] [float] NULL,
[Likelihood_to_Renew_0_10__c] [float] NULL,
[Relocation_Wave__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[B16_Easy_Renew_as_of_3_30__c] [bit] NULL,
[W16_Easy_Renew_as_of_3_30__c] [bit] NULL,
[Alumnus_a__c] [bit] NULL,
[Family_of_Alumnus_a__c] [bit] NULL,
[Family_of_Current_Student__c] [bit] NULL,
[Family_of_Faculty_Staff__c] [bit] NULL,
[Current_Student__c] [bit] NULL,
[Faculty_Staff__c] [bit] NULL,
[SAA_Member__c] [bit] NULL,
[Buck_Cardinal_Club_Member__c] [bit] NULL,
[Former_Student_Athlete__c] [bit] NULL,
[Other_Stanford_Affiliation__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Baseball_Fan__c] [bit] NULL,
[Interested_in_Buck_Cardinal_Club__c] [bit] NULL,
[Family_Status__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Profession__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reason_s_May_Not_Renew__c] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F14_Freshman_STH__c] [bit] NULL,
[F14_Sophomore_STH__c] [bit] NULL,
[Total_Renewable_Seats__c] [float] NULL,
[Email_Quarantine_Reason__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[purlLink__c] [bit] NULL,
[F15_Renewal_Invoice_Mail_Date__c] [date] NULL,
[F15_Relocations_Special_Handling__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Known_Broker_Flag__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Likely_Broker_Flag__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Possible_Broker_Flag__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F14_Deposit_Campaign__c] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F14_Deposit_Campaign_Stage_as_of_4_1_15__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F14_Deposit_Campaign_Reason_Lost__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Deposit_Type__c] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F13_STH__c] [bit] NULL,
[F14_ScholarShare_Plan__c] [bit] NULL,
[F14_Spend__c] [float] NULL,
[F13_Spend__c] [float] NULL,
[F12_Spend__c] [float] NULL,
[F14_F13_F12_Spend__c] [float] NULL,
[F14_Campaign_Reason_Lost__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[B14_Games_Attended_Survey__c] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[B14_Freshman_STH__c] [bit] NULL,
[Football_STH__c] [bit] NULL,
[WBB_STH__c] [bit] NULL,
[Email_Problem__c] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[W14_Games_Attended_Survey__c] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[W14_Freshman_STH__c] [bit] NULL,
[F14_Group_Spend__c] [float] NULL,
[F13_Group_Qty__c] [float] NULL,
[F14_Group_Qty__c] [float] NULL,
[F13_Washington__c] [bit] NULL,
[F13_UCLA__c] [bit] NULL,
[F13_Oregon__c] [bit] NULL,
[F13_Cal__c] [bit] NULL,
[F13_Notre_Dame__c] [bit] NULL,
[B15_Coaching_Staff_Saves_Campaign__c] [bit] NULL,
[Previous_F15_Campaign_Prefers_Partials__c] [bit] NULL,
[F14_Single_Games__c] [float] NULL,
[F13_Single_Games__c] [float] NULL,
[F14_Single_Game_Spend__c] [float] NULL,
[F13_Single_Game_Spend__c] [float] NULL,
[F15_Delivery_Method__c] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F15_Renewals_Stage__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F15_Renewals_Reason_Lost__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F15_Renewals_Owner__c] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[V14_Spend__c] [float] NULL,
[X3_Year_Volleyball_Spend__c] [float] NULL,
[Volleyball_Group_Prospect__c] [bit] NULL,
[S14_Spend__c] [float] NULL,
[X3_Year_Soccer_Spend__c] [float] NULL,
[Soccer_Group_Prospect__c] [bit] NULL,
[dialforce__DS_Date_of_Last_Dispo__c] [date] NULL,
[dialforce__DS_Last_Disposition__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dialforce__DS_Total_Call_Count__c] [float] NULL,
[B14_Spend__c] [float] NULL,
[B14_Season__c] [bit] NULL,
[B14_Mini_Plan__c] [bit] NULL,
[DS_Workflow_Checkbox__c] [bit] NULL,
[DS_Counter_Checkbox__c] [bit] NULL,
[VM_Count__c] [float] NULL,
[Conversation_Count__c] [float] NULL,
[Referral__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_Date_of_Last_Dispo__c] [date] NULL,
[DS_Last_Disposition__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_Total_Call_Count__c] [float] NULL,
[B14_Group__c] [bit] NULL,
[B13_Mini_Plan__c] [bit] NULL,
[B12_Mini_Plan__c] [bit] NULL,
[B12_Spend__c] [float] NULL,
[W12_Spend__c] [float] NULL,
[W14_Spend__c] [float] NULL,
[W13_Season_Tickets__c] [bit] NULL,
[W12_Season_Tickets__c] [bit] NULL,
[W14_Mini_Plan__c] [bit] NULL,
[W13_Mini_Plan__c] [bit] NULL,
[W12_Mini_Plan__c] [bit] NULL,
[W14_Group__c] [bit] NULL,
[DS_Preferred_Phone__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opportunity_DNC__c] [bit] NULL,
[Permanent_DNC__c] [bit] NULL,
[Type_of_Verbal_Commitment__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[B16_Easy_Renew_Form__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EM_Count__c] [float] NULL,
[Personal_EM_Count__c] [float] NULL,
[Total_EM_Count__c] [float] NULL,
[No_Email_Address__c] [bit] NULL,
[F16_Easy_Renew_as_of_1_25__c] [bit] NULL,
[F15_Freshman_STM__c] [bit] NULL,
[F15_Sophomore_STM__c] [bit] NULL,
[Sold_50_of_Family_Plan_in_F15__c] [bit] NULL,
[No_Season_Tickets_Left_in_F15__c] [bit] NULL,
[Received_1_26_Exp_CC_Email__c] [bit] NULL,
[Hasn_t_Opened_ERENEW_Email__c] [bit] NULL,
[Prefers_to_be_Contacted_by_Phone__c] [bit] NULL,
[Prefers_to_be_Contacted_by_Email__c] [bit] NULL,
[Prefers_to_be_Contacted_by_Mail__c] [bit] NULL,
[F16_Easy_Renew_CC_Failed__c] [bit] NULL,
[D15_Mini_Plan__c] [bit] NULL,
[D15_Group__c] [bit] NULL,
[D14_STM__c] [bit] NULL,
[D14_Mini_Plan__c] [bit] NULL,
[D14_Group__c] [bit] NULL,
[D14_D15_Spend__c] [float] NULL,
[STA__c] [bit] NULL,
[RELOCATE__c] [bit] NULL,
[RELORZYA__c] [bit] NULL,
[Burt_F16_Renewals_Account__c] [bit] NULL,
[Multiple_Seatblocks__c] [bit] NULL,
[First_Seatblock__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STA_Special_Handling__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RELOCATE_Special_Handling__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RELORZYA_Special_Handling__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[W16_Easy_Renew_Form__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[B15_Seatblock__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[W15_Seatblock__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[W15_STM__c] [bit] NULL,
[B15_STM__c] [bit] NULL,
[Special_Handling__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RST_Deposit__c] [bit] NULL,
[GST_Deposit__c] [bit] NULL,
[Deposit_Quantity__c] [float] NULL,
[F16_STM__c] [bit] NULL,
[B16_Renewals_Campaign__c] [bit] NULL,
[W16_Renewals_Campaign__c] [bit] NULL,
[F16_DEPP3__c] [bit] NULL,
[F14_RST__c] [bit] NULL,
[F14_GST__c] [bit] NULL,
[F15_Spend__c] [float] NULL,
[F15_Mini_Plan__c] [bit] NULL,
[F14_Mini_Plan__c] [bit] NULL,
[ERENEW_Expired_CC__c] [bit] NULL,
[ERENEW_Email_Non_Open__c] [bit] NULL,
[F16_New_Business_Campaign__c] [bit] NULL,
[B16_PURL__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[W16_PURL__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cardinal_Kids_Day_Promo_Code__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Exclude_from_Campaign_Email_Blasts__c] [bit] NULL,
[DialSource__Date_of_Last_Disposition_DS__c] [date] NULL,
[DialSource__Last_Disposition_DS__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Total_Call_Count_DS__c] [float] NULL,
[Candidate_for_Coaching_Staff_Call__c] [bit] NULL,
[F15_Group_Qty__c] [float] NULL,
[F15_Group_Spend__c] [float] NULL,
[F16_Renewals_Campaign__c] [bit] NULL,
[Preferred_Phone__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lottery_Winner__c] [bit] NULL,
[Proximity_Tier__c] [float] NULL,
[DialSource__Next_Call_DS__c] [datetime] NULL,
[B15_Mini_Plan__c] [bit] NULL,
[B14_STM__c] [bit] NULL,
[B13_STM__c] [bit] NULL,
[DialSource__Datetime_of_Last_Disposition_DS__c] [datetime] NULL,
[V16_Easy_Renew_as_of_6_17_16__c] [bit] NULL,
[S16_Easy_Renew_as_of_6_17_16__c] [bit] NULL,
[Men_s_Soccer_STM__c] [bit] NULL,
[Women_s_Soccer_STM__c] [bit] NULL,
[DS_Click_to_Dial__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F16_Renewals_Opp_Stage__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F16_Renewals_Reason_Lost__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F16_SG_Buyer__c] [bit] NULL,
[B15_Group__c] [bit] NULL,
[W15_Mini_Plan__c] [bit] NULL,
[W15_Group__c] [bit] NULL,
[InstaQueue__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_String_Account_Name__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Acct_Name__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_Test_Phone__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CopyLoadDate] [datetime] NOT NULL CONSTRAINT [DF_ProdCopy_Opportunity] DEFAULT (getdate())
)
GO
ALTER TABLE [prodcopystg].[Opportunity] ADD CONSTRAINT [PK__Opportun__3214EC079EC95158] PRIMARY KEY CLUSTERED  ([Id])
GO
